### PR TITLE
Fixes for Ruby 2.3

### PR DESCRIPTION
**Pull request by ghost**
"type" is now reserved.

### CODE REVIEW

**Comment by jamesottaway** [comment]
What do you mean reserved? Can you show me an example of an error or warning from before you made this change?

**Comment by ghost** [comment]
```
travis@travis-sap-mbp:~ (ruby-2.3.3@test)
[PROD] → gem install yubioath -v '1.2.0'                                                                                                  
Fetching: bindata-2.3.5.gem (100%)
Successfully installed bindata-2.3.5
Successfully installed yubioath-1.2.0
Parsing documentation for bindata-2.3.5
Installing ri documentation for bindata-2.3.5
Parsing documentation for yubioath-1.2.0
Installing ri documentation for yubioath-1.2.0
Done installing documentation for bindata, yubioath after 2 seconds
2 gems installed
travis@travis-sap-mbp:~ (ruby-2.3.3@test)
[PROD] → irb                                                                                                                              
 :001 > require 'yubioath'
NameError: field 'type' is a reserved name in BinData::Array
        from /Users/travis/.rvm/gems/ruby-2.3.3@test/gems/yubioath-1.2.0/lib/yubioath/list.rb:35:in `block in <class:Response>'
        from /Users/travis/.rvm/gems/ruby-2.3.3@test/gems/bindata-2.3.5/lib/bindata/dsl.rb:392:in `instance_eval'
        from /Users/travis/.rvm/gems/ruby-2.3.3@test/gems/bindata-2.3.5/lib/bindata/dsl.rb:392:in `params_from_block'
        from /Users/travis/.rvm/gems/ruby-2.3.3@test/gems/bindata-2.3.5/lib/bindata/dsl.rb:365:in `params_from_field_declaration'
        from /Users/travis/.rvm/gems/ruby-2.3.3@test/gems/bindata-2.3.5/lib/bindata/dsl.rb:347:in `initialize'
        from /Users/travis/.rvm/gems/ruby-2.3.3@test/gems/bindata-2.3.5/lib/bindata/dsl.rb:185:in `new'
        from /Users/travis/.rvm/gems/ruby-2.3.3@test/gems/bindata-2.3.5/lib/bindata/dsl.rb:185:in `parse_and_append_field'
        from /Users/travis/.rvm/gems/ruby-2.3.3@test/gems/bindata-2.3.5/lib/bindata/dsl.rb:124:in `method_missing'
        from /Users/travis/.rvm/gems/ruby-2.3.3@test/gems/bindata-2.3.5/lib/bindata/dsl.rb:46:in `method_missing'
        from /Users/travis/.rvm/gems/ruby-2.3.3@test/gems/yubioath-1.2.0/lib/yubioath/list.rb:32:in `<class:Response>'
        from /Users/travis/.rvm/gems/ruby-2.3.3@test/gems/yubioath-1.2.0/lib/yubioath/list.rb:31:in `<class:List>'
        from /Users/travis/.rvm/gems/ruby-2.3.3@test/gems/yubioath-1.2.0/lib/yubioath/list.rb:6:in `<class:YubiOATH>'
        from /Users/travis/.rvm/gems/ruby-2.3.3@test/gems/yubioath-1.2.0/lib/yubioath/list.rb:5:in `<top (required)>'
        from /Users/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/travis/.rvm/gems/ruby-2.3.3@test/gems/yubioath-1.2.0/lib/yubioath.rb:4:in `<top (required)>'
        from /Users/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from /Users/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from /Users/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from (irb):1
        from /Users/travis/.rvm/rubies/ruby-2.3.3/bin/irb:11:in `<main>'
```

**Comment by ghost** [comment]
Looks like it might actually be BinData not Ruby that is reserving the name "type"

**Comment by jamesottaway** [comment]
Thanks for the clarification. I amended your commit and pushed it straight to `master` here: https://github.com/jamesottaway/yubioath/commit/1710494f5b4490f1cfd3b8df9d06000f76235dcc

The new version should be on RubyGems now, too.

**Comment by ghost** [comment]
Awesome, thanks so much! Also thanks for making this gem, saved me a ton of time 👍

**Comment by jamesottaway** [comment]
No worries, I'm glad someone other than myself is getting use from it.

Out of curiousity, what are you using it for?

**Comment by ghost** [comment]
Using it to generate TOTP for 2 factor authentication to our VPN server.

**Pull request closed without merging**
